# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

production:
  adapter: postgresql
  host: ec2-54-204-7-145.compute-1.amazonaws.com
  database: dfs18rkj7dtg3v
  username: xfhbooznbwhfax
  password: KoiCMTaQwfG0JTDf0By_UployA
  url: postgres://xfhbooznbwhfax:KoiCMTaQwfG0JTDf0By_UployA@ec2-54-204-7-145.compute-1.amazonaws.com:5432/dfs18rkj7dtg3v
  port: 5432
